name: Qodana

on:
  push:
    branches: [ qodana ]
    paths:
      - .github/workflows/qodana.yml

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.0
